Ain
itkpi/events-parser pull request #44
Opened 2016-11-28 20:01 UTC by wack17s

Meet the ain!

2016-11-28 20:46 UTC, webknjaz requested changes
This is insane!

2016-11-28 20:46 UTC, webknjaz commented on LICENSE
> -                                 Apache License
WTF? Fix your editor to leave normal line endings `\n`. And throw away your windows

2016-11-28 20:48 UTC, webknjaz commented
@MaxymVlasov you'd better add `.gitattributes` to prevent stupid end-of-line ending commits.

2016-11-30 14:23 UTC, webknjaz commented
@MaxymVlasov чому не AirBnb code style?

2016-11-30 14:25 UTC, webknjaz requested changes

2016-11-30 14:25 UTC, webknjaz commented on README.md
> +>>>>>>> 6cfe23278a72011242d3f15f5468c4046d1d96fc
WTF?

2016-11-30 14:25 UTC, webknjaz commented on data/blackList.js
> -'use strict'
Still messing w/ EOL

2016-11-30 14:25 UTC, webknjaz commented on data/dataIO.js
> -/**
Same

2016-11-30 14:31 UTC, MaxymVlasov commented
@webknjaz бо доведеться випилит  крапки з комами, напр, а це вже буде не початковий кодстайл.
Да і модулі стандарту є для всього, навіщо заморочуватись?

2016-11-30 14:32 UTC, MaxymVlasov commented
Щодо прекоміта і гітатрібутів - тре мб таки заморочитись  і налаштувати

2016-11-30 14:35 UTC, MaxymVlasov commented on README.md
> +>>>>>>> 6cfe23278a72011242d3f15f5468c4046d1d96fc
Омг. Не помітив.
Філіп, випилюй

А мені доведеться новий ключ згенерити

2016-11-30 14:35 UTC, MaxymVlasov commented on data/blackList.js
> -'use strict'
Ммм?

2016-11-30 14:50 UTC, MaxymVlasov commented on README.md
> +>>>>>>> 6cfe23278a72011242d3f15f5468c4046d1d96fc
Це ж не ключ. Гм

2016-11-30 15:25 UTC, webknjaz commented
https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes @MaxymVlasov

2016-11-30 15:46 UTC, webknjaz commented on README.md
> +>>>>>>> 6cfe23278a72011242d3f15f5468c4046d1d96fc
не впізнав? це хтось не прибрав за собою мітку з мердж конфлікту

2016-11-30 15:46 UTC, webknjaz commented on data/blackList.js
> -'use strict'
`.gitattributes`, що я скинув унизу має все пофіксити

2016-11-30 15:47 UTC, webknjaz commented on data/blackList.js
> -'use strict'
Якщо ні, можеш мене попросити, я допоможу з цим безладом

2016-11-30 15:50 UTC, MaxymVlasov commented
@webknjaz лол)
Зайди в запропоновані іт кпі і узрі там пост двогодинної давності від сене. Там цей лінк теж є.

І джс у цій репі нема

2016-11-30 16:03 UTC, webknjaz commented
Як це нема? https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes#L25

2016-11-30 16:05 UTC, MaxymVlasov commented
@webknjaz
Те про що ти казав є тут
https://help.github.com/articles/dealing-with-line-endings/

2016-11-30 16:07 UTC, MaxymVlasov commented
@webknjaz
І що?
Воно бере raw файл джс і дивиться на нього як на текст. В чому прикол?
Воно  ж так само без цього рядка працюватиме

2016-11-30 16:25 UTC, webknjaz commented
в тому, що не буде діфів безглуздих

2016-11-30 21:19 UTC, MaxymVlasov requested changes

2016-11-30 21:19 UTC, MaxymVlasov commented on data/parse.js
> +    return name || ''
...

```js
const name = src('h1').text() || ''

return name
```

Ретурн має бути якомога простішим.

2016-11-30 21:19 UTC, MaxymVlasov commented on data/parse.js
> +      time = time ? time.replace(/(<span>|<\/span>)/g, '').slice(1, 6) : '00:00'
давай це у більш функціональний стиль, через `const` і дві змінні

2016-11-30 21:19 UTC, MaxymVlasov commented on data/parse.js
> +  price = price ? ' | ' + price : ' | Free'
без ` | Free`
Безкоштовним ціну не вказуємо (могли просто забути повідомити про ціну)

2016-11-30 21:19 UTC, MaxymVlasov commented on main.js
> +    title += price
-

перенеси в `dataIO.sendToApi`, бо це костиль через апі, а не через код парсера

2016-11-30 21:21 UTC, MaxymVlasov reviewed
Ок, дякую)

@webknjaz Апрувниш своє ревью?

2016-11-30 21:22 UTC, MaxymVlasov commented on data/blackList.js
> -'use strict'
спс

2016-11-30 21:27 UTC, webknjaz requested changes

2016-11-30 21:27 UTC, webknjaz commented on data/dataIO.js
> +    if (event.link.slice(21, 25) !== '2016') {
hardcode sucks

2016-11-30 21:27 UTC, webknjaz commented on data/parse.js
> +const cheerio = require("cheerio")
use the same quotation style across commits

2016-11-30 21:27 UTC, webknjaz commented on data/parse.js
> +  return eval(giveConfig[srcFrom].price)
evil.

2016-11-30 21:27 UTC, webknjaz commented on data/parse.js
> +    .attr('datetime').replace(/[^А-Яа-я0-9.-:/$]/g, "")
Uncommon cyrillic letters like Ї may not fit this regexp

2016-11-30 21:28 UTC, webknjaz commented
Психонув і пофіксив переноси

2016-11-30 21:28 UTC, webknjaz commented
@wack17s же вміє `git pull --rebase`?

2016-11-30 21:28 UTC, MaxymVlasov commented on data/parse.js
> +  return eval(giveConfig[srcFrom].price)
I know.

2016-11-30 21:30 UTC, MaxymVlasov commented
@webknjaz а для чого питаєш?

2016-11-30 21:31 UTC, webknjaz commented
ну йому ж це треба буде зробити, коли зробить локальні коміти і помітить, що на ремоуті є нові

2016-11-30 21:35 UTC, MaxymVlasov commented
Тепер точно вміє

2016-11-30 21:44 UTC, MaxymVlasov requested changes

2016-11-30 21:44 UTC, MaxymVlasov commented on data/dataIO.js
> +dataIO.get = (srcFrom, srcName, srcType, srcLink, newJSON, oldJSON) => {
Ти так і не випилив цю штуку -_-
А треба, бо useless

2016-11-30 21:44 UTC, MaxymVlasov commented on data/transform.js
> +    //.replace(/\n/g, '<br>')
?

2016-11-30 21:44 UTC, MaxymVlasov commented on main.js
> +  const getNewData = dataIO.get(srcFrom, srcName, srcType, srcLink, newJSON, oldJSON)
те саме

2016-11-30 21:44 UTC, MaxymVlasov commented on utils.js
> +  switch (month) {
Варто переписати у конструкцію "скільки місяців від сьогодні"
Напр, приходить 0 - беремо те що зараз, 1 - наступний, 2 - через місяць і т.д.

2016-11-30 21:45 UTC, wack17s commented on data/dataIO.js
> +dataIO.get = (srcFrom, srcName, srcType, srcLink, newJSON, oldJSON) => {
там проверка идет по srcFrom

2016-11-30 22:25 UTC, MaxymVlasov commented on data/dataIO.js
> +dataIO.get = (srcFrom, srcName, srcType, srcLink, newJSON, oldJSON) => {
Краще внеси це добро в switch з srcType

І в `ain` не `NUEsrcType: 'json'`.
От жодного разу.

Давай поки заведемо тип `raw(ain)`, а як додаватимемо ще якесь `raw` джерело - узагальнемо.

2016-12-01 16:34 UTC, webknjaz requested changes

2016-12-01 16:34 UTC, webknjaz commented on data/dataIO.js
> +dataIO.get = (srcFrom, srcName, srcType, srcLink, newJSON, oldJSON) => {
вносити зміни в декларацію функції, яка ще в купі місць використовуватися може, з псуванням порядку аргуметів є поганий тон у будь-якому вигляді. найбезпечніший спосіб у такому разі зробити додавання аргументу останнім (**АЛЕ** якщо *справді* треба).

2016-12-01 16:35 UTC, wack17s commented on data/dataIO.js
> +dataIO.get = (srcFrom, srcName, srcType, srcLink, newJSON, oldJSON) => {
@webknjaz @MaxymVlasov я уже переписал это с использованием srcName вместо srcFrom, так что со следующим коммитов все кул будет

2016-12-02 16:49 UTC, webknjaz requested changes

2016-12-02 16:49 UTC, webknjaz commented on data/dataIO.js
> +const cheerio = require("cheerio")
quotes are still different.

2016-12-02 16:49 UTC, webknjaz commented on data/dataIO.js
> +      fs.writeFileSync(newJSON, ainBody)
WTF? Learn how to deal with async code.

2016-12-02 16:49 UTC, webknjaz commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
херня з тих же причин, що й раніше: ламаєш порядок аргументів функції (і навіть юніт тестів не пишеш!)

2016-12-02 16:49 UTC, webknjaz commented on data/parse.js
> +    return name
fix indentation

2016-12-02 16:49 UTC, webknjaz commented on data/parse.js
> +    _log_(`ERROR: AIN have parsing problem in parse.whenStart\n${src}`)
haS

2016-12-02 16:49 UTC, webknjaz commented on main.js
> +   //srcFrom, srcName, srcLink
WTF?

2016-12-02 17:00 UTC, wack17s commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
? почему ломаю, если я прописал этот порядок и в src.js и в main.js?

2016-12-02 17:09 UTC, wack17s commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
@webknjaz ? почему ломаю, если я прописал этот порядок и в src.js и в main.js?

2016-12-02 17:23 UTC, webknjaz commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
1) міг десь забути (можуть бути неочевидні місця, де викликається, напр eval, хай йому грець!)
2) може зламатися десь при мерджі через чиюсь неуважність, я не тільки цю гілку маю на увазі, а й інші, в яких виклики до цього коду. напр, виклик хтось додав, воно конфліктом не вилізло, але при цьому й неправильно вже

2016-12-02 17:33 UTC, MaxymVlasov commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
@webknjaz  Тести скоро почнемо писати.

Орієнтовно - з цих вихідних

2016-12-02 17:33 UTC, wack17s commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
@webknjaz перед каждым коммитом тестирую, написание нормальных тестов в условном туду листе висят, после мерджа аина, просто все затянулось из-за моего нубства и кучи требуеммых изменений после каждого коммита..

2016-12-02 17:54 UTC, MaxymVlasov requested changes

2016-12-02 17:54 UTC, MaxymVlasov commented on data/dataIO.js
> +      res = ainGetLinks(res)
Давай у більш функціонально-читабельному вигляді
Намагайся декларувати всі змінні як константи і давати їм ім'я, що даватиме зрозуміти, що знаходиться після присвоєння. Напр тут: лінки

Заодно сам `res` вище на `const` поміняй

2016-12-02 17:54 UTC, MaxymVlasov commented on data/parse.js
> +  let t = src('.event-head').find('time').eq(1).attr('datetime')
`const`
Неймінг зовсім не допомагає зрозуміти що ж там грепається.

2016-12-02 17:54 UTC, MaxymVlasov commented on data/parse.js
> +  const p = src('.event-head').find('a').parent().next().text()
Знову неймінг хромає.
Взагалі намагай не викоримтовувати ім'я довжиною в 1 символ (окрім лічильників)

2016-12-02 17:54 UTC, MaxymVlasov commented on data/parse.js
> +    .replace(/[^A-Za-z0-9-:/$ ]/g, '').replace(/[\n]/g, ' ')
Воно так не працюватиме.
Аби заматчило `-` - треба ставити його в саиюмому кінці групи, прямо перед `]`

2016-12-02 17:54 UTC, MaxymVlasov commented on data/dataIO.js
> +      fs.writeFileSync(newJSON, ainBody)
Поки хрін з ним.

Перепишеться у наступній ітерації. Зараз весь парсер синхронний. До кінця року має стати асинхронним

2016-12-02 17:54 UTC, MaxymVlasov commented on data/dataIO.js
> +dataIO.sendtoAPI = (title, agenda, social, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName) => {
@webknjaz якщо в тебе щось є готове/на почитати по прекомітам - кинь пліз

2016-12-02 17:54 UTC, MaxymVlasov commented on data/parse.js
> +  const price = p ? ' | ' + p : ''
це реалізація з APi.
Тобі у цій функції теперішне `p` повертати треба.

2016-12-02 17:54 UTC, MaxymVlasov commented on main.js
> +   //srcFrom, srcName, srcLink
@wack17s Да, як ти в тому коменті писав - тре поміняти. Бо не по код-стайлу.
[Постав вже собі лінтер]([http://standardjs.com/index.html#install).

2016-12-02 17:54 UTC, MaxymVlasov commented on utils.js
> +  let year = month === 13 ? nowYear + 1 : nowYear
А якщо я тобі передам 14?)
Або постав перевірку-обмеження, або розширюй, аби воно могло до нескінченності лопатити

2016-12-02 17:54 UTC, MaxymVlasov commented on utils.js
> +  month = month === 13 ? '01' : month
`'01'` 
Можеш просто `1` передати.

2016-12-02 17:58 UTC, wack17s commented on utils.js
> +  month = month === 13 ? '01' : month
@MaxymVlasov а вот и нет, тестил, 1 не работал

2016-12-02 17:59 UTC, wack17s commented on utils.js
> +  let year = month === 13 ? nowYear + 1 : nowYear
@MaxymVlasov поставлю проверку-ограничитель

2016-12-02 18:00 UTC, wack17s commented on data/parse.js
> +  const price = p ? ' | ' + p : ''
@MaxymVlasov api еще не умеет цену, потому ставлю палку, чтоб приписать в тайтл

2016-12-02 18:02 UTC, MaxymVlasov commented on utils.js
> +  month = month === 13 ? '01' : month
@wack17s Може ти щось неправильно передавав?
Бо апі хаває.
Можеш глянути що прилітає з доу, напр, або ручками прописати у [формі на сайті](http://itkpi.pp.ua/events/suggest/)

2016-12-02 20:26 UTC, MaxymVlasov commented on data/dataIO.js
> +      const xmlBody = xml2json.toJson(res.getBody(), {'sanitize': false})
не вгадав)
`xml2json.toJson` повертає `json`, а не `xml`

2016-12-02 20:26 UTC, MaxymVlasov commented on data/parse.js
> +  const time = src('.event-head').find('time').eq(1).attr('datetime') ?
Якщо ти вже юзаєш тетрарний у таких великих виразах, то важається хорошим тоном записувати їх наступним чином:
```js
condition
? do
: else
```

2016-12-02 20:26 UTC, MaxymVlasov commented on data/parse.js
> +  const place = src('div.ven').next().text() === 'Онлайн' ? 'Online' : src('div.ven')
Те саме що і у попередньому

А навіщо ти `Онлайн` на `Online` замінюєш?
По перше, це робота `data/transform.js`, по друге, там вже реалізована зворотня заміна

2016-12-02 20:26 UTC, MaxymVlasov commented on utils.js
>    const nowMonth = new Date().getMonth() + 1
ти двічі тягаєш `new Date` 
Створи об’єкт `data` і  тягай його

2016-12-02 20:37 UTC, wack17s commented on data/dataIO.js
> +      const xmlBody = xml2json.toJson(res.getBody(), {'sanitize': false})
@MaxymVlasov body xml файла, хотел сначала написать просто xml, решил что так будет лучше

2016-12-02 20:40 UTC, MaxymVlasov requested changes

2016-12-02 20:40 UTC, MaxymVlasov commented on data/parse.js
> +
зайвий перенос строки

2016-12-02 20:40 UTC, MaxymVlasov commented on data/parse.js
> +    .attr('datetime').replace(/[^А-Яа-я0-9.-:/$]/g, "")
Тут відбудеться ігнорування усіх символів від `.` і до `:` а не трійки `.-:`
Так і задумувалось?

2016-12-02 20:40 UTC, MaxymVlasov commented on data/parse.js
> +    .replace(/[^A-Za-z0-9:/$ -]/g, '').replace(/[\n]/g, ' ')
Ем. Ти замінюєш кожен символ `\` і  `n` на пробіл...
Здається ти мав на увазі `/\\n/g`

2016-12-02 20:40 UTC, MaxymVlasov commented on main.js
> +        dataIO.sendtoAPI(title, agenda, addInfo, place, regUrl, imgUrl, price, whenStart, whenEnd, onlyDate, srcName)
`price` таки в кінець.
Те саме трохи нижче і в `sendToAPI`

2016-12-02 23:34 UTC, webknjaz commented on utils.js
>    const nowMonth = new Date().getMonth() + 1
@wack17s давай подаруємо Максу словник :)
data == дані

2016-12-03 03:33 UTC, MaxymVlasov commented on utils.js
>    const nowMonth = new Date().getMonth() + 1
ну date, ну йой

2016-12-03 03:35 UTC, MaxymVlasov commented on data/dataIO.js
> +      const xmlBody = xml2json.toJson(res.getBody(), {'sanitize': false})
@wack17s `body xml файла` ось тут: `res.getBody()`

2016-12-03 10:12 UTC, wack17s commented on data/parse.js
> +  const time = src('.event-head').find('time').eq(1).attr('datetime') ?
@MaxymVlasov пацаны из фб пишут так
 ![image](https://cloud.githubusercontent.com/assets/14200710/20858617/ad5a578a-b951-11e6-8588-53868f29051d.png)

2016-12-03 12:32 UTC, MaxymVlasov commented on data/parse.js
> +  const time = src('.event-head').find('time').eq(1).attr('datetime') ?
@wack17s Справедливе зауваження.
Роби як на скріні.

2016-12-03 12:38 UTC, MaxymVlasov commented on data/parse.js
> +  const time = src('.event-head').find('time').eq(1).attr('datetime') ?
@wack17s http://standardjs.com/rules.html
![](https://pp.vk.me/c638518/v638518502/f659/a3M8HcsBPcs.jpg)

2016-12-07 20:05 UTC, wack17s commented on data/dataIO.js
> +      const xmlBody = xml2json.toJson(res.getBody(), {'sanitize': false})
@MaxymVlasov и как мне переименовать это? по моему все логично, body xml файла, по аналогии к ainBody и readableBody json файлов, харднеймить readableXmlBody не вижу смысла

2016-12-07 20:56 UTC, MaxymVlasov commented on data/dataIO.js
> +      const xmlBody = xml2json.toJson(res.getBody(), {'sanitize': false})
@wack17s `jsonBody`

2016-12-11 14:59 UTC, MaxymVlasov approved these changes

2016-12-11 14:59 UTC, MaxymVlasov commented on data/parse.js
> +  ? src('.event-head').find('time').eq(1).attr('datetime')
Відступ додай, по кодстайлу
http://standardjs.com/rules.html

2016-12-11 14:59 UTC, MaxymVlasov commented on data/parse.js
> +  ? 'Онлайн'
те саме

2016-12-11 15:07 UTC, MaxymVlasov requested changes

2016-12-11 15:07 UTC, MaxymVlasov commented on data/dataIO.js
> +      const jsonBody = xml2json.toJson(res.getBody(), {'sanitize': false})
Ти в попередньому рядку  додав `.getBody()`, а тут не прибрав. Треба прибрати

2016-12-11 15:07 UTC, MaxymVlasov commented on data/parse.js
> +function ainTitle (src) {
Чому це не можна запхнути в `src.js`?

2016-12-11 15:07 UTC, MaxymVlasov commented on src.js
> +    price: '',
Ти не додав це поле до блоку-коментаря з поясненнями, що згори цього об’єкту

2016-12-11 16:28 UTC, MaxymVlasov commented on data/parse.js
> +  let date = '9999-09-09'
Remove this

2016-12-11 16:28 UTC, MaxymVlasov commented on data/parse.js
> +    return date
```js
return '9999-09-09'
```

2016-12-11 16:28 UTC, MaxymVlasov commented on data/parse.js
> +  date = `${yyyy}-${mm}-${dd}`
```js
const date
```

2016-12-11 16:28 UTC, MaxymVlasov commented on data/parse.js
> +    .replace(/[^A-Za-z0-9:/$ -]/g, '').replace(/\\n/g, ' ')
Ти в першому `replace` видаляєш усі символи, крім латиничних, цифер, двокрапки, слеша. долару,  тире і пробілу?

Чи ти щось інше замислював?

2016-12-11 16:31 UTC, wack17s commented on data/parse.js
> +    return date
харкод же @MaxymVlasov

2016-12-11 16:33 UTC, wack17s commented on data/parse.js
> +    .replace(/[^A-Za-z0-9:/$ -]/g, '').replace(/\\n/g, ' ')
@MaxymVlasov +

2016-12-11 16:34 UTC, MaxymVlasov commented on data/parse.js
> +    return date
@wack17s який юзається тільки в `if`, а не в усій функції, як до цього.

Якщо в тебе є краща ідея, як доправити івент в апі без креша - кажи.

2016-12-13 20:21 UTC, MaxymVlasov approved these changes

2016-12-13 20:23 UTC, MaxymVlasov commented
@webknjaz В тебе є ще якісь зауваження?

2016-12-14 20:49 UTC, webknjaz commented
@MaxymVlasov як щодо конфліктів? ) до речі. гітхаб днями навчився веб-інтерфейс для виправлення їх показувати

2016-12-14 20:50 UTC, webknjaz commented
@wack17s як будеш мерджити обери **Squash and merge** на стрілочці в самій кнопці мерджа

2016-12-14 23:21 UTC, webknjaz commented
І відредагуй короткий і довгий коміт меседжі щоб виглядали адекватно. Ось інструкції:
* [ ] http://chris.beams.io/posts/git-commit/
* [ ] http://alistapart.com/article/the-art-of-the-commit
* [ ] https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
* [ ] https://wiki.openstack.org/wiki/GitCommitMessages
* [ ] http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

2016-12-15 20:34 UTC, merged