Generate app version at build time
itkpi/events-parser pull request #52
Opened 2016-12-27 15:22 UTC by webknjaz

* Wiped out statsd garbage
* Removed runtime git dependency by generating the version during build
* Made app retrieve the version either via env var or via reading it from the build-specific file

2016-12-27 17:09 UTC, MaxymVlasov requested changes

2016-12-27 17:09 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Воно ж тепер інакше версію видає
```
 vMAJOR.MINOR.PATH-%branch name%
```
Замість
```
vMAJOR.MINOR.PATH-%branch name%-%number of commits from last tag%-%commit hash%
```

Куди автоверсіонування ділось?

2016-12-27 17:09 UTC, MaxymVlasov commented on utils.js
> +  let app_version = process.env.APP_VERSION
1. camelCase
2. Краще `const`

2016-12-27 17:11 UTC, webknjaz commented on utils.js
> +  let app_version = process.env.APP_VERSION
Пробував, але це не константа

2016-12-27 17:11 UTC, webknjaz commented on utils.js
> +  return app_version
У ваггу

2016-12-27 17:11 UTC, MaxymVlasov commented on utils.js
> +  return app_version
А де подивитись логи?

2016-12-27 17:12 UTC, webknjaz commented on utils.js
> +  return app_version
Ти мабуть path із patch плутаєш

2016-12-27 17:13 UTC, MaxymVlasov commented on utils.js
> +  let app_version = process.env.APP_VERSION
В плані не константа?
Змінні середовища ж підкидуються до запуску програми і під час її роботи не мають змінюватись

2016-12-27 17:15 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Ой, поправ пліз, у JSDoc до цієї функції

2016-12-27 17:18 UTC, webknjaz commented on utils.js
> +  return app_version
Логи? Можеш запустити `vagga _run events monkey sh` і глянути той файл

2016-12-27 17:19 UTC, webknjaz commented on utils.js
> +  let app_version = process.env.APP_VERSION
Нижче дивися

2016-12-27 17:22 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Мені бажано знати, на якому коміті ламається обробка івенту (regexp’и усякі) у продакшені, без крешу самого контейнера. 

Як це потім у логах можна буде подивитись?

2016-12-27 17:25 UTC, MaxymVlasov commented on utils.js
> +  return app_version
```bash
➜  events-parser git:(feature/buildtime-version-generation) vagga _run eventsmonkey sh
Container "eventsmonkey" not found
➜  events-parser git:(feature/buildtime-version-generation) vagga _run events monkey sh
Container "events" not found
➜  events-parser git:(feature/buildtime-version-generation) vagga _run events monkey.sh
Container "events" not found
➜  events-parser git:(feature/buildtime-version-generation) vagga _run eventsmonkey.sh 
Usage:
    vagga _run [OPTIONS] CONTAINER COMMAND [ARG ...]
vagga _run: Argument command is required
```

2016-12-27 17:28 UTC, webknjaz commented on utils.js
> +  return app_version
Там не крапка, а пробіл

2016-12-27 17:29 UTC, webknjaz commented on utils.js
> +  return app_version
Назва контейнера по пам'яті і з телефону, може Т9, сам перевір

2016-12-27 17:32 UTC, webknjaz commented on utils.js
> +  return app_version
А, ти про ті логи. Ну можна sentry якийсь прикрутити, але вагга не має зв'язку з продом, тому не тут обговорювати

2016-12-27 17:34 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Ну блін, а мені саме на проді треба

2016-12-27 17:35 UTC, webknjaz commented on utils.js
> +  return app_version
Це не стосується PR цього

2016-12-27 17:36 UTC, MaxymVlasov commented on utils.js
> +  return app_version
```sh
➜  events-parser git:(feature/buildtime-version-generation) vagga _run eventsparser sh
/work #
```
Ок, щось відбулось. Єдине питання: що?

Тут ще лізти в доку ваги треба, чи що?

2016-12-27 17:38 UTC, MaxymVlasov commented on utils.js
> +  let app_version = process.env.APP_VERSION
Так воно ж все-одно ніби перед `npm start` виконується...
Не розумію.

2016-12-27 17:43 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Стосується. Ти мені випилив робоче версіонування з проду і вліпив незрозуміло що

2016-12-27 21:54 UTC, webknjaz commented on utils.js
> +  return app_version
@rrader 🆘

2016-12-28 07:09 UTC, webknjaz commented on utils.js
> +  let app_version = process.env.APP_VERSION
даний шматок коду **(який ти коментуєш)** читає зі змінної середовища, якщо вона є, а інакше з файлу. оскільки в цю змінну можливе повторне присвоєння, то вона не є константою.

2016-12-28 07:11 UTC, webknjaz commented on utils.js
> +  return app_version
`_run` запускає вказану програму в контейнері, ти просто в шелл підключився був внутрішній.

2016-12-28 14:52 UTC, webknjaz commented on utils.js
> +  return app_version
Рома показав мені як це на проді запускається (я думав, він ваггу не крутить там), тому я додав команду для виводу поточної версії апки і зможу її реюзнути там. Крім того, я вже бачу що там можна буде покращити :)

2016-12-28 19:17 UTC, MaxymVlasov commented on utils.js
> +  return app_version
Ой, а навіщо ти затираєш старий код?
Це ж бранча: скільки сюди не ліпи, все-одно змерджиться один коміт.
А так знову все з нуля дивитись і не видно де зміни то)

2016-12-29 08:46 UTC, webknjaz commented on utils.js
> +  return app_version
Не завжди треба squash, тут мабуть буде ребейз. Недобре робити неатомарні коміти. Тому тримаю марку "1 зміна == 1 коміт"

2016-12-29 14:15 UTC, webknjaz commented
давай вже апрув його і буде можна частиною прода займатися

2016-12-29 19:33 UTC, MaxymVlasov commented on utils.js
> + * Pattern: vMAJOR.MINOR.PATH-%branch name%-%number of commits from last tag%-%commit hash%.
Виправ, будь ласка, `PATH` на `PATCH` - моя обдруківка

2016-12-29 19:42 UTC, MaxymVlasov commented on utils.js
> +  return app_version
А я тримаю марку "одна зміна - одна бранча"

Не знаю навіщо ти впилив ревертінг і версіонування в одну бранчу

2016-12-29 19:54 UTC, webknjaz commented on utils.js
> + * Pattern: vMAJOR.MINOR.PATH-%branch name%-%number of commits from last tag%-%commit hash%.
Там залежить від певних умов

2016-12-29 19:55 UTC, webknjaz commented on utils.js
> +  return app_version
Бо результатом має бути одразу робоча зміна

2016-12-29 20:06 UTC, MaxymVlasov approved these changes

2016-12-29 20:08 UTC, MaxymVlasov commented on utils.js
> + * Pattern: vMAJOR.MINOR.PATH-%branch name%-%number of commits from last tag%-%commit hash%.
Тоді краще ці умови задокоментувати, бо раніше воно від тегів відштовхувалось, а від чого зараз - трохи не зрозуміло. Те що потрапляє в ран-тайм виглядає як `v0.5.1-feature/buildtime-version-generation`

2016-12-29 21:32 UTC, webknjaz commented on utils.js
> + * Pattern: vMAJOR.MINOR.PATH-%branch name%-%number of commits from last tag%-%commit hash%.
Так я переписав шматок js на sh без зміни логіки, глянь сам

2016-12-29 21:40 UTC, MaxymVlasov commented on vagga.yaml
> +          ver=$ver-$sub_ver
Та в тому то і справа, що ніби має працювати, проте значення `sub_ver` ігноруються О_0

2016-12-29 21:47 UTC, webknjaz commented on vagga.yaml
> +          ver=$ver-$sub_ver
я запускав у себе в терміналі цей шматок перед комітом і в мене працювало. тож імовірно в середовищі справа

2016-12-29 21:56 UTC, merged

2016-12-29 21:58 UTC, MaxymVlasov commented on vagga.yaml
> +          ver=$ver-$sub_ver
В звичайному терміналі - працює. Як перевірити у vagga - хз. 
```sh
➜  events-parser git:(feature/buildtime-version-generation) vagga _run eventsparser sh
/work # ver=`git describe | awk -F- '{print$1}'`-`git re
> v-parse --abbrev-ref HEAD`
/bin/sh: git: not found
/bin/sh: git: not found
/bin/sh: v-parse: not found
/work # git describe | awk -F- '{print$2"\n"$3}' | while
>  read sub_ver
> do
> ver=$ver-$sub_ver
> done
/bin/sh: git: not found
/work # $ver
/bin/sh: -: not found
/work #
```

2016-12-29 22:42 UTC, webknjaz commented on vagga.yaml
> +          ver=$ver-$sub_ver
у вагга там не працює дійсно, зараз розколупую чому так. таке враження, що у `while` свій власний скоуп

2016-12-29 22:45 UTC, MaxymVlasov commented on vagga.yaml
> +          ver=$ver-$sub_ver
Коли пофіксиш - підійми, будь ласка, мінорну версію в `package.json`.
І тег приліпи